/**
 * Client entity from MK-Auth API
 * Contains all fields returned by /api/cliente/listar endpoint
 */
export interface Client {
  id: string;
  nome: string;
  email: string;
  endereco: string;
  bairro: string;
  cidade: string;
  cep: string;
  estado: string;
  cpf_cnpj: string;
  ie: string | null;
  fone: string;
  obs: string | null;
  nascimento: string;
  estado_civil: string;
  cadastro: string;
  login: string;
  tipo: string;
  night: string;
  aviso: string;
  foto: string;
  venc: string;
  mac: string | null;
  complemento: string;
  ip: string | null;
  ramal: string;
  rg: string;
  isento: string;
  celular: string;
  bloqueado: string;
  autoip: string;
  automac: string;
  ipvsix: string | null;
  conta: string;
  plano: string;
  send: string;
  cli_ativado: string;
  simultaneo: string;
  turbo: string;
  comodato: string;
  contrato: string;
  observacao: string;
  chavetipo: string;
  chave: string | null;
  ssid: string | null;
  senha: string;
  desconto: string;
  numero: string | null;
  endereco_res: string;
  numero_res: string | null;
  bairro_res: string;
  cidade_res: string;
  cep_res: string;
  estado_res: string;
  complemento_res: string;
  responsavel: string | null;
  nome_pai: string | null;
  nome_mae: string | null;
  expedicao_rg: string | null;
  naturalidade: string | null;
  acessacen: string;
  pessoa: string;
  acrescimo: string;
  equipamento: string;
  vendedor: string | null;
  nextel: string | null;
  accesslist: string;
  resumo: string;
  grupo: string;
  codigo: string;
  prilanc: string;
  tipobloq: string;
  adesao: string;
  mbdisco: string;
  sms: string;
  zap: string;
  ltrafego: string;
  planodown: string;
  ligoudown: string;
  statusdown: string;
  statusturbo: string;
  nome_res: string;
  coordenadas: string;
  rem_obs: string | null;
  valor_sva: string;
  opcelular: string;
  dias_corte: string;
  user_ip: string | null;
  user_mac: string | null;
  data_ip: string | null;
  data_mac: string | null;
  last_update: string;
  data_bloq: string | null;
  tags: string | null;
  tecnico: string | null;
  data_ins: string | null;
  altsenha: string;
  geranfe: string;
  mesref: string;
  ipfall: string | null;
  tit_abertos: string;
  parc_abertas: string;
  tipo_pessoa: string;
  mac_serial: string | null;
  status_corte: string;
  plano15: string;
  celular2: string | null;
  pgaviso: string;
  porta_olt: string | null;
  caixa_herm: string | null;
  porta_splitter: string | null;
  onu_ont: string | null;
  switch: string | null;
  tit_vencidos: string;
  interface: string | null;
  login_atend: string;
  cidade_ibge: string;
  estado_ibge: string;
  data_desbloq: string;
  pool_name: string;
  pool6: string | null;
  pgcorte: string;
  rec_email: string;
  dot_ref: string | null;
  conta_cartao: string;
  termo: string;
  opcelular2: string;
  plano_bloqc: string;
  armario_olt: string | null;
  tipo_cliente: string;
  uuid_cliente: string;
  data_desativacao: string | null;
  tipo_cob: string;
  fortunus: string;
  gsici: string;
  local_dici: string;
  uuid: string;
}

/**
 * Paginated response from /api/cliente/listar endpoint
 */
export interface ClientListResponse {
  total_registros: number;
  consulta_atual: number;
  pagina_atual: number;
  total_paginas: number;
  clientes: Client[];
}
